### PR TITLE
12.18.1

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
Any ideas why windows is failing?

```
Extracting download
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 824, in tar_xf
    libarchive.extract_file(tarball, flags)
  File "C:\Miniconda36-x64\lib\site-packages\libarchive\extract.py", line 70, in extract_file
    extract_entries(archive, flags)
  File "C:\Miniconda36-x64\lib\site-packages\libarchive\extract.py", line 50, in extract_entries
    write_header(write_p, entry._entry_p)
  File "C:\Miniconda36-x64\lib\site-packages\libarchive\ffi.py", line 124, in check_int
    raise archive_error(args[0], retcode)
  File "C:\Miniconda36-x64\lib\site-packages\libarchive\ffi.py", line 108, in archive_error
    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)
libarchive.exception.ArchiveError: Can't create '\\?\C:\bld\tmp7fnp539j\Trilinos-trilinos-release-12-14-1\INSTALL' (errno=22, retcode=-25, archive_p=46638038112)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2343, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1417, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\render.py", line 628, in try_download
    source.provide(metadata)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\source.py", line 652, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\source.py", line 148, in unpack
    tar_xf(src_path, tmpdir)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 830, in tar_xf
    _tar_xf_fallback(tarball, dir_path)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 778, in _tar_xf_fallback
    t.extractall(path=dir_path)
  File "C:\Miniconda36-x64\lib\tarfile.py", line 2008, in extractall
    numeric_owner=numeric_owner)
  File "C:\Miniconda36-x64\lib\tarfile.py", line 2050, in extract
    numeric_owner=numeric_owner)
  File "C:\Miniconda36-x64\lib\tarfile.py", line 2120, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Miniconda36-x64\lib\tarfile.py", line 2161, in makefile
    with bltn_open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\bld\\tmp7fnp539j\\Trilinos-trilinos-release-12-14-1\\packages\\kokkos-kernels\\src\\impl\\generated_specializations_cpp\\gauss_seidel_apply\\KokkosSparse_gauss_seidel_apply_eti_spec_inst_Kokkos_complex_double__int_int64_t_LayoutLeft_Cuda_CudaHostPinnedSpace_CudaHostPinnedSpace.cpp'
Command exited with code 1
```

**Comment by isuruf** [comment]
That file path is too long in windows.

**Comment by looooo** [comment]
Seems like there is not much response. Is it possible to handle this problem with the recipe (by using a different build-directory)?

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

can we merge this in this state? Windows is failing, but I guess we cannot do much about it.

**Comment by looooo** [comment]
windows: 
```
CMake Error at cmake_install.cmake:56 (file):
-- Installing: D:/bld/trilinos_1574101714727/_h_env/Library/lib/cmake/tribits/examples/MockTrilinos/packages/sacado/cmake/Dependencies.cmake
  file INSTALL cannot read symlink
```
Anyone interested into fixing windows?

**Comment by looooo** [comment]
@wfspotz 
@jschueller 
anybody able to merge this PR? I guess we can resolve windows also later if needed.

**Comment by pyt-viper** [comment]
So, Windows has never been supported by the conda-forge Trilinos package.  For the first go-around, with v12.10, the issue was MPI.  It may be possible to get this working, but we'll put it off to the future.  This PR has been replaced by PR #24.

**Pull request closed without merging**
